apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 4003
    hostPort: 30003
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 4004
    hostPort: 30004
    listenAddress: "0.0.0.0"
    protocol: tcp